# Generated by Django 6.0.6 on 2026-06-20 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_id', models.CharField(choices=[('chat', 'Daily Check-In'), ('anxiety', 'Anxiety & Panic'), ('sleep', 'Sleep & Insomnia'), ('grief', 'Grief & Loss'), ('social', 'Social Anxiety'), ('adhd', 'ADHD Support'), ('recovery', 'Addiction & Recovery'), ('trauma', 'Trauma & PTSD'), ('burnout', 'Burnout & Stress'), ('postpartum', 'Postpartum Wellness')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('mood_label', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('stressed', 'Stressed'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('mood_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('crisis_flag', models.BooleanField(default=False)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrisisFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('trigger_text', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crisis_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('stressed', 'Stressed'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('scan', 'Face Scan'), ('ai_detected', 'AI Detected')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mood_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
